[package]
name = "nanolabo_wasm"
version = "0.1.0"
authors = ["Olivier Giniaux <oginiaux@gmail.com>"]
edition = "2018"

[lib]
name = "nanolabo_wasm"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
nanomesh = { path = "../main" }
wasm-bindgen = "0.2.80"