[package]
name = "nanomesh_macros"
version = "0.1.0"
authors = ["Olivier Giniaux <oginiaux@gmail.com>"]
edition = "2018"

[lib]
name = "nanomesh_macros"
path = "lib.rs"
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"