on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

name: nanomesh-rust-wasm

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Build 🛠
        run: cargo build --verbose

      - name: Test 🧪
        run: cargo test --verbose

      - name: Pack 📦
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
          cd wasm
          wasm-pack build --release --target web
          rm pkg/.gitignore

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: wasm
