[package]
name = "decimation-benchmark"
version = "0.1.0"
edition = "2018"
resolver = "2"

[dependencies]
nanomesh = { path="../nanomesh" }
nanoview = { path="../nanoview" }
img_hash = "3.2"
image = "0.23.14"
pollster = "0.2.4"
tokio = { version = "1", features = ["full"] }